// ─── UBIGEO / residencia del paciente — constantes y catálogos compartidos ─────
// Fuente ÚNICA para backend (validación) y frontend (autocomplete). El catálogo de
// distritos vive como JSON aparte (grande); aquí van los códigos especiales, el
// catálogo de países y la normalización de búsqueda que usan ambos autocompletes.

/** Fila especial de Ubigeo: paciente que reside FUERA del Perú (exige paisResidencia). */
export const UBIGEO_EXTRANJERO = '999999';
/** Fila especial de Ubigeo: el paciente no precisa su distrito. */
export const UBIGEO_NO_PRECISA = '999998';

/** Normaliza para búsqueda tipográfica: sin tildes, minúsculas, espacios colapsados. */
export function normalizarBusqueda(s: string): string {
  return (s ?? '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
}

export interface Pais {
  codigo: string; // ISO 3166-1 alpha-2
  nombre: string; // en español
}

/** Catálogo ISO 3166-1 alpha-2 en español, SIN "PE" (un residente en Perú tiene distrito). */
export const PAISES: Pais[] = [
  { codigo: 'AF', nombre: 'Afganistán' },
  { codigo: 'AL', nombre: 'Albania' },
  { codigo: 'DE', nombre: 'Alemania' },
  { codigo: 'AD', nombre: 'Andorra' },
  { codigo: 'AO', nombre: 'Angola' },
  { codigo: 'AG', nombre: 'Antigua y Barbuda' },
  { codigo: 'SA', nombre: 'Arabia Saudita' },
  { codigo: 'DZ', nombre: 'Argelia' },
  { codigo: 'AR', nombre: 'Argentina' },
  { codigo: 'AM', nombre: 'Armenia' },
  { codigo: 'AU', nombre: 'Australia' },
  { codigo: 'AT', nombre: 'Austria' },
  { codigo: 'AZ', nombre: 'Azerbaiyán' },
  { codigo: 'BS', nombre: 'Bahamas' },
  { codigo: 'BD', nombre: 'Bangladés' },
  { codigo: 'BB', nombre: 'Barbados' },
  { codigo: 'BH', nombre: 'Baréin' },
  { codigo: 'BE', nombre: 'Bélgica' },
  { codigo: 'BZ', nombre: 'Belice' },
  { codigo: 'BJ', nombre: 'Benín' },
  { codigo: 'BY', nombre: 'Bielorrusia' },
  { codigo: 'BO', nombre: 'Bolivia' },
  { codigo: 'BA', nombre: 'Bosnia y Herzegovina' },
  { codigo: 'BW', nombre: 'Botsuana' },
  { codigo: 'BR', nombre: 'Brasil' },
  { codigo: 'BN', nombre: 'Brunéi' },
  { codigo: 'BG', nombre: 'Bulgaria' },
  { codigo: 'BF', nombre: 'Burkina Faso' },
  { codigo: 'BI', nombre: 'Burundi' },
  { codigo: 'BT', nombre: 'Bután' },
  { codigo: 'CV', nombre: 'Cabo Verde' },
  { codigo: 'KH', nombre: 'Camboya' },
  { codigo: 'CM', nombre: 'Camerún' },
  { codigo: 'CA', nombre: 'Canadá' },
  { codigo: 'QA', nombre: 'Catar' },
  { codigo: 'TD', nombre: 'Chad' },
  { codigo: 'CL', nombre: 'Chile' },
  { codigo: 'CN', nombre: 'China' },
  { codigo: 'CY', nombre: 'Chipre' },
  { codigo: 'CO', nombre: 'Colombia' },
  { codigo: 'KM', nombre: 'Comoras' },
  { codigo: 'KP', nombre: 'Corea del Norte' },
  { codigo: 'KR', nombre: 'Corea del Sur' },
  { codigo: 'CI', nombre: 'Costa de Marfil' },
  { codigo: 'CR', nombre: 'Costa Rica' },
  { codigo: 'HR', nombre: 'Croacia' },
  { codigo: 'CU', nombre: 'Cuba' },
  { codigo: 'DK', nombre: 'Dinamarca' },
  { codigo: 'DM', nombre: 'Dominica' },
  { codigo: 'EC', nombre: 'Ecuador' },
  { codigo: 'EG', nombre: 'Egipto' },
  { codigo: 'SV', nombre: 'El Salvador' },
  { codigo: 'AE', nombre: 'Emiratos Árabes Unidos' },
  { codigo: 'ER', nombre: 'Eritrea' },
  { codigo: 'SK', nombre: 'Eslovaquia' },
  { codigo: 'SI', nombre: 'Eslovenia' },
  { codigo: 'ES', nombre: 'España' },
  { codigo: 'US', nombre: 'Estados Unidos' },
  { codigo: 'EE', nombre: 'Estonia' },
  { codigo: 'SZ', nombre: 'Esuatini' },
  { codigo: 'ET', nombre: 'Etiopía' },
  { codigo: 'PH', nombre: 'Filipinas' },
  { codigo: 'FI', nombre: 'Finlandia' },
  { codigo: 'FJ', nombre: 'Fiyi' },
  { codigo: 'FR', nombre: 'Francia' },
  { codigo: 'GA', nombre: 'Gabón' },
  { codigo: 'GM', nombre: 'Gambia' },
  { codigo: 'GE', nombre: 'Georgia' },
  { codigo: 'GH', nombre: 'Ghana' },
  { codigo: 'GD', nombre: 'Granada' },
  { codigo: 'GR', nombre: 'Grecia' },
  { codigo: 'GT', nombre: 'Guatemala' },
  { codigo: 'GN', nombre: 'Guinea' },
  { codigo: 'GQ', nombre: 'Guinea Ecuatorial' },
  { codigo: 'GW', nombre: 'Guinea-Bisáu' },
  { codigo: 'GY', nombre: 'Guyana' },
  { codigo: 'HT', nombre: 'Haití' },
  { codigo: 'HN', nombre: 'Honduras' },
  { codigo: 'HK', nombre: 'Hong Kong' },
  { codigo: 'HU', nombre: 'Hungría' },
  { codigo: 'IN', nombre: 'India' },
  { codigo: 'ID', nombre: 'Indonesia' },
  { codigo: 'IQ', nombre: 'Irak' },
  { codigo: 'IR', nombre: 'Irán' },
  { codigo: 'IE', nombre: 'Irlanda' },
  { codigo: 'IS', nombre: 'Islandia' },
  { codigo: 'IL', nombre: 'Israel' },
  { codigo: 'IT', nombre: 'Italia' },
  { codigo: 'JM', nombre: 'Jamaica' },
  { codigo: 'JP', nombre: 'Japón' },
  { codigo: 'JO', nombre: 'Jordania' },
  { codigo: 'KZ', nombre: 'Kazajistán' },
  { codigo: 'KE', nombre: 'Kenia' },
  { codigo: 'KG', nombre: 'Kirguistán' },
  { codigo: 'KI', nombre: 'Kiribati' },
  { codigo: 'XK', nombre: 'Kosovo' },
  { codigo: 'KW', nombre: 'Kuwait' },
  { codigo: 'LA', nombre: 'Laos' },
  { codigo: 'LS', nombre: 'Lesoto' },
  { codigo: 'LV', nombre: 'Letonia' },
  { codigo: 'LB', nombre: 'Líbano' },
  { codigo: 'LR', nombre: 'Liberia' },
  { codigo: 'LY', nombre: 'Libia' },
  { codigo: 'LI', nombre: 'Liechtenstein' },
  { codigo: 'LT', nombre: 'Lituania' },
  { codigo: 'LU', nombre: 'Luxemburgo' },
  { codigo: 'MO', nombre: 'Macao' },
  { codigo: 'MK', nombre: 'Macedonia del Norte' },
  { codigo: 'MG', nombre: 'Madagascar' },
  { codigo: 'MY', nombre: 'Malasia' },
  { codigo: 'MW', nombre: 'Malaui' },
  { codigo: 'MV', nombre: 'Maldivas' },
  { codigo: 'ML', nombre: 'Malí' },
  { codigo: 'MT', nombre: 'Malta' },
  { codigo: 'MA', nombre: 'Marruecos' },
  { codigo: 'MU', nombre: 'Mauricio' },
  { codigo: 'MR', nombre: 'Mauritania' },
  { codigo: 'MX', nombre: 'México' },
  { codigo: 'FM', nombre: 'Micronesia' },
  { codigo: 'MD', nombre: 'Moldavia' },
  { codigo: 'MC', nombre: 'Mónaco' },
  { codigo: 'MN', nombre: 'Mongolia' },
  { codigo: 'ME', nombre: 'Montenegro' },
  { codigo: 'MZ', nombre: 'Mozambique' },
  { codigo: 'MM', nombre: 'Myanmar (Birmania)' },
  { codigo: 'NA', nombre: 'Namibia' },
  { codigo: 'NR', nombre: 'Nauru' },
  { codigo: 'NP', nombre: 'Nepal' },
  { codigo: 'NI', nombre: 'Nicaragua' },
  { codigo: 'NE', nombre: 'Níger' },
  { codigo: 'NG', nombre: 'Nigeria' },
  { codigo: 'NO', nombre: 'Noruega' },
  { codigo: 'NZ', nombre: 'Nueva Zelanda' },
  { codigo: 'OM', nombre: 'Omán' },
  { codigo: 'NL', nombre: 'Países Bajos' },
  { codigo: 'PK', nombre: 'Pakistán' },
  { codigo: 'PW', nombre: 'Palaos' },
  { codigo: 'PS', nombre: 'Palestina' },
  { codigo: 'PA', nombre: 'Panamá' },
  { codigo: 'PG', nombre: 'Papúa Nueva Guinea' },
  { codigo: 'PY', nombre: 'Paraguay' },
  { codigo: 'PL', nombre: 'Polonia' },
  { codigo: 'PT', nombre: 'Portugal' },
  { codigo: 'PR', nombre: 'Puerto Rico' },
  { codigo: 'GB', nombre: 'Reino Unido' },
  { codigo: 'CF', nombre: 'República Centroafricana' },
  { codigo: 'CZ', nombre: 'República Checa' },
  { codigo: 'CG', nombre: 'República del Congo' },
  { codigo: 'CD', nombre: 'República Democrática del Congo' },
  { codigo: 'DO', nombre: 'República Dominicana' },
  { codigo: 'RW', nombre: 'Ruanda' },
  { codigo: 'RO', nombre: 'Rumania' },
  { codigo: 'RU', nombre: 'Rusia' },
  { codigo: 'WS', nombre: 'Samoa' },
  { codigo: 'KN', nombre: 'San Cristóbal y Nieves' },
  { codigo: 'SM', nombre: 'San Marino' },
  { codigo: 'VC', nombre: 'San Vicente y las Granadinas' },
  { codigo: 'LC', nombre: 'Santa Lucía' },
  { codigo: 'ST', nombre: 'Santo Tomé y Príncipe' },
  { codigo: 'SN', nombre: 'Senegal' },
  { codigo: 'RS', nombre: 'Serbia' },
  { codigo: 'SC', nombre: 'Seychelles' },
  { codigo: 'SL', nombre: 'Sierra Leona' },
  { codigo: 'SG', nombre: 'Singapur' },
  { codigo: 'SY', nombre: 'Siria' },
  { codigo: 'SO', nombre: 'Somalia' },
  { codigo: 'LK', nombre: 'Sri Lanka' },
  { codigo: 'ZA', nombre: 'Sudáfrica' },
  { codigo: 'SD', nombre: 'Sudán' },
  { codigo: 'SS', nombre: 'Sudán del Sur' },
  { codigo: 'SE', nombre: 'Suecia' },
  { codigo: 'CH', nombre: 'Suiza' },
  { codigo: 'SR', nombre: 'Surinam' },
  { codigo: 'TH', nombre: 'Tailandia' },
  { codigo: 'TW', nombre: 'Taiwán' },
  { codigo: 'TZ', nombre: 'Tanzania' },
  { codigo: 'TJ', nombre: 'Tayikistán' },
  { codigo: 'TL', nombre: 'Timor Oriental' },
  { codigo: 'TG', nombre: 'Togo' },
  { codigo: 'TO', nombre: 'Tonga' },
  { codigo: 'TT', nombre: 'Trinidad y Tobago' },
  { codigo: 'TN', nombre: 'Túnez' },
  { codigo: 'TM', nombre: 'Turkmenistán' },
  { codigo: 'TR', nombre: 'Turquía' },
  { codigo: 'TV', nombre: 'Tuvalu' },
  { codigo: 'UA', nombre: 'Ucrania' },
  { codigo: 'UG', nombre: 'Uganda' },
  { codigo: 'UY', nombre: 'Uruguay' },
  { codigo: 'UZ', nombre: 'Uzbekistán' },
  { codigo: 'VU', nombre: 'Vanuatu' },
  { codigo: 'VA', nombre: 'Vaticano' },
  { codigo: 'VE', nombre: 'Venezuela' },
  { codigo: 'VN', nombre: 'Vietnam' },
  { codigo: 'YE', nombre: 'Yemen' },
  { codigo: 'DJ', nombre: 'Yibuti' },
  { codigo: 'ZM', nombre: 'Zambia' },
  { codigo: 'ZW', nombre: 'Zimbabue' },
];

/** ¿`codigo` es un país válido del catálogo? (para la validación del backend, A4). */
export function esPaisValido(codigo: string): boolean {
  return PAISES.some((p) => p.codigo === codigo);
}

/** Nombre en español de un código ISO-2 (o el código si no está en el catálogo). */
export function nombrePais(codigo: string | null | undefined): string | null {
  if (!codigo) return null;
  return PAISES.find((p) => p.codigo === codigo)?.nombre ?? codigo;
}
